### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by petrockblog** [Aloshi/ES-config#10]
I started to [post](https://github.com/petrockblog/RetroPie-Setup/issues/198#issuecomment-20528901) these issues in the issues list of RetroPie Setup Script, but I think it belongs more at this place:

I attempted to start ES-config with the command ./es-config --scriptdir /home/pi/supplementary/ES-config/scripts --configpath /home/pi/congis/all --resourcedir /home/pi/supplementary/ES-config/resources, but this leads to a segmentation fault. Also, I am not sure how to use the --settings parameter. --settings /home/pi/.emulationstation/es_input.cfgdoes not work.
Besides that, the tool looks very promising.

I just realized that I cannot even start ES-config without any parameters ("./es-config"). However, it worked for one or two times before ... Are there any temporary files that I could delete?

Just FYI: I have updated the RetroPie Script such that you can install ES-config from within the source-based menu now. However, as you can also read above, this is in an experimental stage right now.

**Comment by Aloshi** [comment]
I'll try and look into this tomorrow night.  Thank you for the report!

**Comment by Aloshi** [comment]
I can't seem to reproduce the segfault...hmm.

The [settings](https://github.com/Aloshi/ES-config#settings) parameter is basically a way to load a bunch of arguments that would otherwise be passed in through command-line by an XML file.  I figured it would be a little easier to generate/modify a settings.xml than a huge single-line list of command-line arguments.

For example, this settings.xml should work:

```
<changeConfigPath from="retroarch.cfg" to="/home/pi/RetroPie/configs/all/retroarch.cfg" />
<changeConfigPath from="dgen.cfg" to="/home/pi/RetroPie/configs/dgen/dgenrc" />
<changeConfigPath from="gngeo.rc" to="whereverGnGeoConfigsGo" />
```

The launch script would become

```
pushd $rootdir/supplementary/ES-config
#should load settings from $rootdir/supplementary/ES-config/settings.xml
#if you don't supply the "--settings [path]" argument, no settings XML file will be loaded!
./esconfig --settings settings.xml   
popd
```

With "/home/pi/RetroPie" replaced with $rootdir during generation from retropie_setup.sh.
You also don't need to pass a scriptdir or resourcedir if you use pushd/popd as you are in the launch script.

The `--configpath [from] [to]` command "redirects" a config write path ([e.g. this](https://github.com/Aloshi/ES-config/blob/master/scripts/retroarch_config.xml#L7)) to somewhere else.  You need to specify EITHER in the settings XML file (e.g. `<changeConfigPath from="retroarch.cfg" to="/home/pi/RetroPie/configs/all/retroarch.cfg" />`) OR as an argument (e.g. `--configpath retroarch.cfg /home/pi/RetroPie/configs/all/retroarch.cfg`), or the file will just get saved to ./[NAME].

Also, ES-config doesn't produce any cache/saved settings files.

**Comment by petrockblog** [comment]
All right then, I deleted everything recompiled again and used `./esconfig --settings settings.xml`. It works now!

ES-config is installed per default with RetroPie now and I will also include it in the next release of the SD-card image. I think this is a huge step forward to make it easier in the end for people to configure their controls :-)
